import Foundation

public enum SupportedLanguage: String, CaseIterable, Codable, Identifiable, Sendable {
    case english = "en"
    case french = "fr"
    case german = "de"
    case spanish = "es"

    public var id: String {
        rawValue
    }

    public var displayName: String {
        switch self {
        case .english: "English"
        case .french: "Français"
        case .german: "Deutsch"
        case .spanish: "Español"
        }
    }

    public var flag: String {
        switch self {
        case .english: "🇬🇧"
        case .french: "🇫🇷"
        case .german: "🇩🇪"
        case .spanish: "🇪🇸"
        }
    }

    public var locale: Locale {
        Locale(identifier: rawValue)
    }
}

public final class LocalizationManager: @unchecked Sendable {
    public static let shared = LocalizationManager()

    private let lock = NSLock()
    private var storedLanguage: SupportedLanguage = .english

    public var currentLanguage: SupportedLanguage {
        self.lock.lock()
        defer { self.lock.unlock() }
        return self.storedLanguage
    }

    private init() {}

    public func setLanguage(_ language: SupportedLanguage) {
        self.lock.lock()
        self.storedLanguage = language
        self.lock.unlock()
    }

    public func detectSystemLanguage() -> SupportedLanguage {
        let preferred = Locale.preferredLanguages.first ?? "en"
        let code = String(preferred.prefix(2)).lowercased()
        return SupportedLanguage.allCases.first { $0.rawValue == code } ?? .english
    }

    public func localized(_ key: String) -> String {
        translations[self.currentLanguage]?[key] ?? key
    }
}

// MARK: - Translation Dictionaries

private let translations: [SupportedLanguage: [String: String]] = [
    .english: [
        "appearance.dark": "Dark",
        "appearance.light": "Light",
        "appearance.system": "System",
        "backend.nativeSwiftSSH": "Native Swift SSH",
        "backend.systemSSH": "System SSH",
        "common.no": "No",
        "common.none": "None",
        "common.server": "server",
        "common.yes": "Yes",

        // General
        "settings.general": "General",
        "settings.about": "About",
        "settings.language": "Language",
        "settings.appearance": "Appearance",
        "settings.behavior": "Behavior",
        "settings.transfers": "Transfers",
        "settings.notifications": "Notifications",

        // Settings labels
        "settings.showHiddenFiles": "Show hidden files",
        "settings.confirmBeforeDelete": "Confirm before delete",
        "settings.confirmBeforeOverwrite": "Confirm before overwrite",
        "settings.checkUpdatesOnStartup": "Check for updates on startup",
        "settings.backgroundNotifications": "Background notifications",
        "settings.transferConcurrency": "Transfer concurrency",
        "settings.remoteBackend": "Remote backend",
        "settings.appIcon": "App icon",
        "settings.theme": "Theme",
        "settings.defaultSort": "Default sort",
        "settings.languagePicker": "App language",
        "settings.showInspector": "Show inspector",
        "settings.showTransferQueue": "Show transfer queue",
        "settings.showSidebar": "Show sidebar",
        "settings.showFileExtensions": "Show file extensions",
        "settings.foldersFirst": "Folders first",
        "settings.sortBy": "Sort by",
        "settings.ascending": "Ascending",
        "settings.browser": "Browser",
        "settings.panels": "Panels",

        // Backend descriptions
        "settings.backend.native": "Experimental: native SFTP supports password and private-key workflows; use System SSH for SSH agent auth.",
        "settings.backend.system": "Recommended: uses macOS SSH shell tools with strict host verification, SSH agent support, and rsync transfers.",

        // Browser
        "browser.local": "Local",
        "browser.remote": "Remote",
        "browser.refresh": "Refresh",
        "browser.refreshRemote": "Refresh Remote",
        "browser.upload": "Upload",
        "browser.download": "Download",
        "browser.compare": "Compare",
        "browser.newFolder": "New Folder",
        "browser.viewOptions": "View Options",
        "browser.inspector": "Inspector",
        "browser.refreshHint": "Refreshes the local file list.",
        "browser.refreshRemoteHint": "Refreshes the remote file list.",
        "browser.uploadHint": "Uploads the selected local item to the current remote folder.",
        "browser.downloadHint": "Downloads the selected remote item to the current local folder.",
        "browser.compareHint": "Compares the current local and remote folders.",
        "browser.connectToServer": "Connect to a server",
        "browser.filterFiles": "Filter files...",
        "browser.itemCount": "%d items",
        "browser.noFilterResults": "No matching files",
        "browser.noFilterResultsMessage": "Adjust the filter to show files in this pane.",
        "browser.noRemoteConnection": "No remote connection",
        "browser.noRemoteConnectionMessage": "Select a saved server or create a new SFTP connection.",

        // Connection
        "connection.connect": "Connect",
        "connection.connecting": "Connecting...",
        "connection.disconnect": "Disconnect",
        "connection.new": "New",
        "connection.more": "More",
        "connection.edit": "Edit",
        "connection.favorite": "Favorite",
        "connection.bookmark": "Bookmark",
        "connection.terminal": "Terminal",
        "connection.noServer": "No Server Selected",
        "connection.connected": "Connected",
        "connection.disconnected": "Disconnected",
        "connection.failed": "Failed",
        "connection.cancelling": "Cancelling",
        "connection.reconnecting": "Reconnecting",
        "connection.connectHint": "Connects to the selected saved server.",
        "connection.newHint": "Opens a new connection form with credentials.",
        "connection.editHint": "Edit the selected server.",
        "connection.addFavHint": "Add the selected server to favorites.",
        "connection.removeFavHint": "Remove the selected server from favorites.",
        "connection.bookmarkHint": "Save the current local and remote paths as a bookmark.",
        "connection.terminalHint": "Opens an SSH session in Terminal.",
        "connection.disconnectHint": "Disconnect from the current server.",
        "connection.connectionStatus": "Connection status: %@",

        // Sidebar
        "sidebar.driftline": "Driftline",
        "sidebar.newConnection": "New Connection",
        "sidebar.saveServer": "Save Server",
        "sidebar.savedServers": "Saved Servers",
        "sidebar.favorites": "Favorites",
        "sidebar.bookmarks": "Bookmarks",
        "sidebar.recent": "Recent",
        "sidebar.noSavedServers": "No saved servers",
        "sidebar.markFavorites": "Mark servers as favorites",
        "sidebar.noBookmarks": "No bookmarks saved",
        "sidebar.noBookmarksDetail": "Add folders to quickly access them.",
        "sidebar.noRecent": "No recent connections",
        "sidebar.quickConnect": "Quick Connect",
        "sidebar.recentServers": "Recent Servers",

        // Transfer
        "transfer.queued": "Queued",
        "transfer.done": "Done",
        "transfer.failed": "Failed",
        "transfer.cancelled": "Cancelled",

        // Tab
        "tab.newConnection": "New Connection",
        "tab.closeTab": "Close Tab?",
        "tab.close": "Close Tab",
        "tab.cancel": "Cancel",
        "tab.closeConfirm.connected": "The connection to %@ is still active. Closing this tab will disconnect.",
        "tab.closeConfirm.connecting": "The connection to %@ is connecting. Closing this tab will disconnect.",
        "tab.closeConfirm.reconnecting": "The connection to %@ is reconnecting. Closing this tab will disconnect.",
        "tab.closeConfirm.default": "The connection to %@ has an active connection. Closing this tab will disconnect.",
        "tab.closeAction": "Close tab",

        // Update
        "update.available": "Update Available",
        "update.later": "Later",
        "update.download": "Download Update",
        "update.message": "Driftline %@ is available. You are running %@.",
        "update.notificationBody": "Version %@ is ready to download.",
        "update.notificationTitle": "Driftline Update Available",
        "update.upToDate": "Driftline is up to date.",
        "update.checkFailed": "Could not check for updates:",

        // Delete
        "delete.title": "Delete Item?",
        "delete.message": "This item will be deleted.",
        "delete.delete": "Delete",
        "delete.cancel": "Cancel",

        // File operations
        "file.newFolder": "New Folder",
        "file.renameItem": "Rename Item",
        "file.newLocalFolder": "New local Folder",
        "file.newRemoteFolder": "New remote Folder",
        "file.newSourceFolder": "New %@ Folder",
        "fileKind.file": "File",
        "fileKind.folder": "Folder",
        "fileKind.symbolicLink": "Symbolic Link",
        "fileKind.unknown": "Unknown",

        // Commands menu
        "menu.file": "File",
        "menu.newConnection": "New Connection",
        "menu.newTab": "New Tab",
        "menu.closeTab": "Close Tab",
        "menu.connection": "Connection",
        "menu.quickConnect": "Quick Connect",
        "menu.connectSelected": "Connect Selected Server",
        "menu.openSSH": "Open SSH in Terminal",
        "menu.reconnectLast": "Reconnect Last",
        "menu.saveConnection": "Save Current Connection",
        "menu.transfer": "Transfer",
        "menu.upload": "Upload",
        "menu.download": "Download",
        "menu.compareFolders": "Compare Folders",
        "menu.showInspector": "Show Inspector",
        "menu.viewOptions": "View Options",
        "menu.help": "Help",
        "menu.checkUpdates": "Check for Updates",
        "menu.revealDiagnostics": "Reveal Diagnostics Log",
        "menu.copy": "Copy",
        "menu.paste": "Paste",
        "menu.aboutDriftline": "About Driftline",
        "menu.edit": "Edit",
        "menu.duplicate": "Duplicate",
        "menu.delete": "Delete",

        // Toast messages
        "toast.upToDate": "Driftline is up to date.",
        "toast.copiedSingle": "Copied %@.",
        "toast.copiedMulti": "Copied %d items.",
        "toast.syncStartedSingle": "Started 1 sync transfer.",
        "toast.syncStartedMulti": "Started %d sync transfers.",
        "toast.favoriteAdded": "Added to favorites.",
        "toast.favoriteRemoved": "Removed from favorites.",
        "toast.bookmarkSaved": "Saved bookmark.",
        "toast.nativeSSHSwitch": "Switched to Native Swift SSH for password authentication.",

        // Notifications
        "notification.serverDisconnectedBody": "%@ is no longer reachable.",
        "notification.serverDisconnectedTitle": "Server Disconnected",
        "notification.transferCompletedBody": "%@ finished on %@.",
        "notification.transferCompletedTitle": "%@ %@",
        "notification.transferFailedBody": "%@ failed on %@.",
        "notification.transferFailedTitle": "%@ Failed",

        // Alert titles
        "alert.checkUpdatesTitle": "Couldn\'t Check for Updates",
        "alert.unsupportedTitle": "Unsupported Action",
        "alert.notConnectedTitle": "Not Connected",
        "alert.noServerTitle": "No Server Selected",
        "alert.bookmarkNotFoundTitle": "Bookmark Not Found",
        "alert.favoriteFailedTitle": "Couldn\'t Update Favorite",
        "alert.bookmarkSaveFailedTitle": "Couldn\'t Save Bookmark",
        "alert.copyFailedTitle": "Couldn\'t Copy",

        // Alert messages
        "alert.unsupportedMsg": "Remote-to-remote copy is not supported yet.",
        "alert.notConnectedMsg": "Connect to a server before comparing folders.",
        "alert.noServerMsg": "Select a saved server or create a new connection.",
        "alert.bookmarkNotFoundMsg": "Bookmark named %@ was not found.",

        // Startup error
        "startup.failedTitle": "Couldn\'t Load Driftline",
        "startup.failedDescription": "An error occurred while loading the application.",
        "startup.retry": "Try Again",

        // App
        "app.name": "Driftline",
        "alert.ok": "OK",

        // Sidebar context menu
        "sidebar.contextConnect": "Connect",
        "sidebar.contextEdit": "Edit",

        // Browser pane
        "browser.upOneFolder": "Up One Folder",
        "browser.refreshPane": "Refresh %@",
        "browser.emptyRemote": "No Remote Listing",
        "browser.emptyLocal": "This Folder Is Empty",
        "browser.emptyRemoteMessage": "Create a connection, select a saved server, then press Connect.",
        "browser.emptyLocalMessage": "Create a folder or choose another local path.",
        "browser.goTo": "Go to %@",
        "browser.macintoshHD": "Macintosh HD",
        "browser.loading": "Loading...",
        "browser.loadingAccessibility": "Loading",
        "browser.column.name": "Name",
        "browser.column.size": "Size",
        "browser.column.type": "Type",
        "browser.column.modified": "Modified",
        "browser.fileBrowser": "%@ file browser",
        "browser.copyPath": "Copy Path",
        "browser.revealFinder": "Reveal in Finder",
        "browser.getInfo": "Get Info",
        "browser.rename": "Rename",
        "browser.delete": "Delete",
        "browser.modifiedAccessibility": "Modified %@",
        "browser.selectedAccessibility": "%@ selected",
        "browser.column.accessibility": "%@: %@",

        // Transfer panel
        "transfer.column.status": "Status",
        "transfer.column.progress": "Progress",
        "transfer.column.direction": "Direction",
        "transfer.column.source": "Source",
        "transfer.column.destination": "Destination",
        "transfer.column.server": "Server",
        "transfer.column.action": "Action",
        "transfer.cancelTransfer": "Cancel Transfer",
        "transfer.cancelTransferAccessibility": "Cancel transfer",
        "transfer.completed": "Completed",
        "transfer.noTransfers": "No transfers yet",
        "transfer.emptyMessage": "Uploads and downloads will appear here.",
        "transfer.transfers": "Transfers",
        "transfer.filter": "Transfer filter",
        "transfer.filter.active": "Active",
        "transfer.filter.all": "All",
        "transfer.filter.completed": "Completed",
        "transfer.filter.failed": "Failed",
        "transfer.noFilteredTransfers": "No transfers in this view",
        "transfer.noFilteredTransfersMessage": "Choose another transfer filter.",
        "transfer.cancelActive": "Cancel Active",
        "transfer.retryFailed": "Retry Failed",
        "transfer.clearFailed": "Clear Failed",
        "transfer.clearCompleted": "Clear Completed",
        "transfer.cancelActiveHelp": "Cancel Active",
        "transfer.retryFailedHelp": "Retry Failed",
        "transfer.clearFailedHelp": "Clear Failed",
        "transfer.clearCompletedHelp": "Clear Completed",
        "transfer.cancelsActiveHint": "Cancels active transfers.",
        "transfer.retriesFailedHint": "Retries failed transfers.",
        "transfer.downloaded": "Downloaded",
        "transfer.uploaded": "Uploaded",

        // Transfer conflict
        "conflict.title": "Transfer Conflict",
        "conflict.existsAt": "An item already exists at:",
        "conflict.existingDestination": "Existing destination",
        "conflict.renameDestination": "Rename destination",
        "conflict.renameHint": "Enter a new destination filename for this transfer only.",
        "conflict.applySingle": "Apply Skip or Overwrite to %d remaining conflict",
        "conflict.applyPlural": "Apply Skip or Overwrite to %d remaining conflicts",
        "conflict.applyHint": "Rename always applies only to the current conflict.",
        "conflict.skip": "Skip",
        "conflict.overwrite": "Overwrite",
        "conflict.transferRenamed": "Transfer as Renamed",
        "conflict.skipHelpSingle": "Skip this transfer.",
        "conflict.skipHelpMulti": "Skip this and all remaining conflicts.",
        "conflict.skipHint": "Leaves the existing item unchanged.",
        "conflict.overwriteHelpSingle": "Overwrite this destination.",
        "conflict.overwriteHelpMulti": "Overwrite this and all remaining conflicts.",
        "conflict.overwriteHint": "Starts the transfer and replaces the existing destination item.",
        "conflict.renameHelp": "Transfer this item using the rename field.",

        // Sync preview
        "sync.done": "Done",
        "sync.closeHint": "Closes the folder comparison.",
        "sync.matching": "Matching",
        "sync.localOnly": "Local only",
        "sync.remoteOnly": "Remote only",
        "sync.changed": "Changed",
        "sync.changedConflicts": "Changed conflicts",
        "sync.conflictHint": "Controls how changed files are handled when both sides already have an item.",
        "sync.planned": "%d planned",
        "sync.runPlan": "Run Plan",
        "sync.runPlanHint": "Starts selected uploads and downloads.",
        "sync.onlyLocal": "Only Local",
        "sync.onlyRemote": "Only Remote",
        "sync.nothingToUpload": "Nothing to upload.",
        "sync.nothingToDownload": "Nothing to download.",
        "sync.none": "None",
        "sync.all": "All",
        "sync.toggleAllHint": "Toggles all items in this section.",
        "sync.setAll": "Set All",
        "sync.skip": "Skip",
        "sync.uploadLocalVersions": "Upload Local Versions",
        "sync.downloadRemoteVersions": "Download Remote Versions",
        "sync.setAllHint": "Choose whether local or remote changed versions should win.",
        "sync.noDifferences": "No size or type differences.",
        "sync.action": "Action",
        "sync.ask": "Ask",
        "sync.replace": "Replace",
        "sync.skipChanged": "Skip Changed",

        // Host trust
        "trust.title": "Trust Host?",
        "trust.algorithm": "Algorithm",
        "trust.fingerprint": "Fingerprint",
        "trust.warning": "Only trust this host if the fingerprint matches a value you verified out of band.",
        "trust.trustAndConnect": "Trust and Connect",
        "trust.hint": "Stores this fingerprint in Driftline known hosts and reconnects.",

        // File operation prompt
        "fileOperation.name": "Name",
        "fileOperation.save": "Save",
        "fileOperation.cancel": "Cancel",

        // Server profile editor
        "profile.section.server": "Server",
        "profile.section.authentication": "Authentication",
        "profile.section.paths": "Paths",
        "profile.section.metadata": "Metadata",
        "profile.displayName": "Display Name",
        "profile.host": "Host",
        "profile.protocol": "Protocol",
        "profile.port": "Port",
        "profile.group": "Group",
        "profile.favorite": "Favorite",
        "profile.username": "Username",
        "profile.method": "Method",
        "profile.auth.agent": "SSH Agent",
        "profile.auth.none": "None",
        "profile.auth.password": "Password",
        "profile.auth.privateKey": "Private Key",
        "profile.password": "Password",
        "profile.privateKey": "Private Key",
        "profile.privateKeyPath": "Private Key Path",
        "profile.choose": "Choose...",
        "profile.storePassphrase": "Store passphrase in Keychain",
        "profile.privateKeyPassphrase": "Private Key Passphrase",
        "profile.noAuth": "None",
        "profile.passwordNote": "Password is stored in Keychain. Driftline automatically uses the Native Swift SSH backend for password-based connections.",
        "profile.remotePath": "Remote Default Path",
        "profile.localPath": "Local Default Path",
        "profile.tags": "Tags",
        "profile.notes": "Notes",
        "profile.tagsPrompt": "production, website",
        "profile.saveConnect": "Save & Connect",
        "profile.save": "Save",
        "profile.newServer": "New Server",

        // View options
        "viewOptions.browser": "Browser",
        "viewOptions.panels": "Panels",

        // Inspector
        "inspector.selection": "Selection",
        "inspector.actions": "Actions",
        "inspector.activity": "Activity",
        "inspector.connection": "Connection",
        "inspector.copyRemotePath": "Copy Remote Path",
        "inspector.chooseServer": "Choose a server from the sidebar to view information.",
        "inspector.lastActivity": "Last Activity",
        "inspector.name": "Name",
        "inspector.noItemSelected": "No item selected",
        "inspector.noServerSelected": "No server selected",
        "inspector.path": "Path",
        "inspector.permissions": "Permissions",
        "inspector.quickLook": "Quick Look",
        "inspector.server": "Server",
        "inspector.type": "Type",
        "inspector.size": "Size",
        "inspector.source": "Source",
        "inspector.selectItem": "Select a local or remote item to view details and actions.",
        "inspector.state": "State",
        "inspector.protocol": "Protocol",
        "inspector.localPath": "Local Path",
        "inspector.remotePath": "Remote Path",

        // Stats dashboard
        "stats.uploads": "Uploads",
        "stats.downloads": "Downloads",
        "stats.lastConnectionFormat": "Last connection: %@",
        "stats.uploaded": "Uploaded",
        "stats.downloaded": "Downloaded",
        "stats.active": "Active",
        "stats.failed": "Failed",
        "stats.lastConnection": "Last Connection",
        "stats.up": "Up",
        "stats.down": "Down",

        // About
        "about.tagline": "Native file transfer, calmly secure.",
        "about.freeMessage": "Driftline is entirely free. If it helps you, feel free to donate.",
        "about.donate": "Donate on Ko-fi",
        "about.checking": "Checking...",
        "about.checkForUpdates": "Check for Updates",
        "about.diagnostics": "Diagnostics",
        "about.version": "Version %@ (%@)",
    ],
    .french: [
        "appearance.dark": "Sombre",
        "appearance.light": "Clair",
        "appearance.system": "Système",
        "backend.nativeSwiftSSH": "SSH natif Swift",
        "backend.systemSSH": "SSH système",
        "common.no": "Non",
        "common.none": "Aucun",
        "common.server": "serveur",
        "common.yes": "Oui",
        "settings.general": "Général",
        "settings.about": "À propos",
        "settings.language": "Langue",
        "settings.appearance": "Apparence",
        "settings.behavior": "Comportement",
        "settings.transfers": "Transferts",
        "settings.notifications": "Notifications",
        "settings.showHiddenFiles": "Afficher les fichiers cachés",
        "settings.confirmBeforeDelete": "Confirmer avant suppression",
        "settings.confirmBeforeOverwrite": "Confirmer avant écrasement",
        "settings.checkUpdatesOnStartup": "Vérifier les mises à jour au démarrage",
        "settings.backgroundNotifications": "Notifications en arrière-plan",
        "settings.transferConcurrency": "Transferts simultanés",
        "settings.remoteBackend": "Backend distant",
        "settings.appIcon": "Icône de l'app",
        "settings.theme": "Thème",
        "settings.defaultSort": "Tri par défaut",
        "settings.languagePicker": "Langue de l'application",
        "settings.showInspector": "Afficher l'inspecteur",
        "settings.showTransferQueue": "Afficher la file de transfert",
        "settings.showSidebar": "Afficher la barre latérale",
        "settings.showFileExtensions": "Afficher les extensions",
        "settings.foldersFirst": "Dossiers en premier",
        "settings.sortBy": "Trier par",
        "settings.ascending": "Croissant",
        "settings.browser": "Navigateur",
        "settings.panels": "Panneaux",
        "settings.backend.native": "Expérimental : SFTP natif prend en charge les workflows par mot de passe et clé privée ; utilisez SSH système pour l'agent SSH.",
        "settings.backend.system": "Recommandé : utilise les outils SSH shell macOS avec vérification stricte de l'hôte, support agent SSH, et transferts rsync.",
        "browser.local": "Local",
        "browser.remote": "Distant",
        "browser.refresh": "Actualiser",
        "browser.refreshRemote": "Actualiser distant",
        "browser.upload": "Téléverser",
        "browser.download": "Télécharger",
        "browser.compare": "Comparer",
        "browser.newFolder": "Nouveau dossier",
        "browser.viewOptions": "Options d'affichage",
        "browser.inspector": "Inspecteur",
        "browser.refreshHint": "Actualise la liste des fichiers locaux.",
        "browser.refreshRemoteHint": "Actualise la liste des fichiers distants.",
        "browser.uploadHint": "Téléverse l'élément local sélectionné vers le dossier distant.",
        "browser.downloadHint": "Télécharge l'élément distant sélectionné vers le dossier local.",
        "browser.compareHint": "Compare les dossiers local et distant actuels.",
        "browser.connectToServer": "Se connecter à un serveur",
        "browser.filterFiles": "Filtrer les fichiers…",
        "browser.itemCount": "%d éléments",
        "browser.noFilterResults": "Aucun fichier correspondant",
        "browser.noFilterResultsMessage": "Ajustez le filtre pour afficher les fichiers de ce volet.",
        "browser.noRemoteConnection": "Aucune connexion distante",
        "browser.noRemoteConnectionMessage": "Sélectionnez un serveur enregistré ou créez une nouvelle connexion SFTP.",
        "connection.connect": "Connecter",
        "connection.connecting": "Connexion...",
        "connection.disconnect": "Déconnecter",
        "connection.new": "Nouveau",
        "connection.more": "Plus",
        "connection.edit": "Modifier",
        "connection.favorite": "Favori",
        "connection.bookmark": "Marque-page",
        "connection.terminal": "Terminal",
        "connection.noServer": "Aucun serveur sélectionné",
        "connection.connected": "Connecté",
        "connection.disconnected": "Déconnecté",
        "connection.failed": "Échec",
        "connection.cancelling": "Annulation",
        "connection.reconnecting": "Reconnexion",
        "connection.connectHint": "Se connecte au serveur sauvegardé sélectionné.",
        "connection.newHint": "Ouvre un formulaire de nouvelle connexion.",
        "connection.editHint": "Modifier le serveur sélectionné.",
        "connection.addFavHint": "Ajouter le serveur sélectionné aux favoris.",
        "connection.removeFavHint": "Retirer le serveur sélectionné des favoris.",
        "connection.bookmarkHint": "Enregistrer les chemins local et distant actuels.",
        "connection.terminalHint": "Ouvre une session SSH dans Terminal.",
        "connection.disconnectHint": "Se déconnecter du serveur actuel.",
        "connection.connectionStatus": "État de la connexion : %@",
        "sidebar.driftline": "Driftline",
        "sidebar.newConnection": "Nouvelle connexion",
        "sidebar.saveServer": "Enregistrer le serveur",
        "sidebar.savedServers": "Serveurs enregistrés",
        "sidebar.favorites": "Favoris",
        "sidebar.bookmarks": "Marque-pages",
        "sidebar.recent": "Récents",
        "sidebar.noSavedServers": "Aucun serveur enregistré",
        "sidebar.markFavorites": "Marquer des serveurs comme favoris",
        "sidebar.noBookmarks": "Aucun marque-page enregistré",
        "sidebar.noBookmarksDetail": "Ajoutez des dossiers pour y accéder rapidement.",
        "sidebar.noRecent": "Aucune connexion récente",
        "sidebar.quickConnect": "Connexion rapide",
        "sidebar.recentServers": "Serveurs récents",
        "transfer.queued": "En attente",
        "transfer.done": "Terminé",
        "transfer.failed": "Échec",
        "transfer.cancelled": "Annulé",
        "tab.newConnection": "Nouvelle connexion",
        "tab.closeTab": "Fermer l'onglet ?",
        "tab.close": "Fermer",
        "tab.cancel": "Annuler",
        "tab.closeConfirm.connected": "La connexion à %@ est toujours active. Fermer cet onglet va déconnecter.",
        "tab.closeConfirm.connecting": "La connexion à %@ est en cours. Fermer cet onglet va déconnecter.",
        "tab.closeConfirm.reconnecting": "La reconnexion à %@ est en cours. Fermer cet onglet va déconnecter.",
        "tab.closeConfirm.default": "La connexion à %@ est active. Fermer cet onglet va déconnecter.",
        "tab.closeAction": "Fermer l'onglet",
        "update.available": "Mise à jour disponible",
        "update.later": "Plus tard",
        "update.download": "Télécharger la mise à jour",
        "update.message": "Driftline %@ est disponible. Vous utilisez la version %@.",
        "update.notificationBody": "La version %@ est prête à être téléchargée.",
        "update.notificationTitle": "Mise à jour Driftline disponible",
        "update.upToDate": "Driftline est à jour.",
        "update.checkFailed": "Impossible de vérifier les mises à jour :",
        "delete.title": "Supprimer ?",
        "delete.message": "Cet élément sera supprimé.",
        "delete.delete": "Supprimer",
        "delete.cancel": "Annuler",
        "file.newFolder": "Nouveau dossier",
        "file.renameItem": "Renommer",
        "file.newLocalFolder": "Nouveau dossier local",
        "file.newRemoteFolder": "Nouveau dossier distant",
        "file.newSourceFolder": "Nouveau dossier %@",
        "fileKind.file": "Fichier",
        "fileKind.folder": "Dossier",
        "fileKind.symbolicLink": "Lien symbolique",
        "fileKind.unknown": "Inconnu",
        "menu.file": "Fichier",
        "menu.newConnection": "Nouvelle connexion",
        "menu.newTab": "Nouvel onglet",
        "menu.closeTab": "Fermer l'onglet",
        "menu.connection": "Connexion",
        "menu.quickConnect": "Connexion rapide",
        "menu.connectSelected": "Connecter le serveur sélectionné",
        "menu.openSSH": "Ouvrir SSH dans Terminal",
        "menu.reconnectLast": "Reconnecter le dernier",
        "menu.saveConnection": "Enregistrer la connexion",
        "menu.transfer": "Transfert",
        "menu.upload": "Téléverser",
        "menu.download": "Télécharger",
        "menu.compareFolders": "Comparer les dossiers",
        "menu.showInspector": "Afficher l'inspecteur",
        "menu.viewOptions": "Options d'affichage",
        "menu.help": "Aide",
        "menu.checkUpdates": "Vérifier les mises à jour",
        "menu.revealDiagnostics": "Afficher le journal de diagnostic",
        "menu.copy": "Copier",
        "menu.paste": "Coller",
        "menu.aboutDriftline": "À propos de Driftline",
        "menu.edit": "Modifier",
        "menu.duplicate": "Dupliquer",
        "menu.delete": "Supprimer",

        "toast.upToDate": "Driftline est à jour.",
        "toast.copiedSingle": "%@ copié.",
        "toast.copiedMulti": "%d éléments copiés.",
        "toast.syncStartedSingle": "1 transfert de synchronisation démarré.",
        "toast.syncStartedMulti": "%d transferts de synchronisation démarrés.",
        "toast.favoriteAdded": "Ajouté aux favoris.",
        "toast.favoriteRemoved": "Retiré des favoris.",
        "toast.bookmarkSaved": "Marque-page enregistré.",
        "toast.nativeSSHSwitch": "Basculé vers SSH natif Swift pour l\'authentification par mot de passe.",
        "notification.serverDisconnectedBody": "%@ n\'est plus joignable.",
        "notification.serverDisconnectedTitle": "Serveur déconnecté",
        "notification.transferCompletedBody": "%@ terminé sur %@.",
        "notification.transferCompletedTitle": "%@ %@",
        "notification.transferFailedBody": "%@ a échoué sur %@.",
        "notification.transferFailedTitle": "%@ échoué",
        "alert.checkUpdatesTitle": "Vérification des mises à jour impossible",
        "alert.unsupportedTitle": "Action non prise en charge",
        "alert.notConnectedTitle": "Non connecté",
        "alert.noServerTitle": "Aucun serveur sélectionné",
        "alert.bookmarkNotFoundTitle": "Marque-page introuvable",
        "alert.favoriteFailedTitle": "Impossible de modifier le favori",
        "alert.bookmarkSaveFailedTitle": "Impossible d\'enregistrer le marque-page",
        "alert.copyFailedTitle": "Impossible de copier",
        "alert.unsupportedMsg": "La copie de distant à distant n\'est pas encore prise en charge.",
        "alert.notConnectedMsg": "Connectez-vous à un serveur avant de comparer les dossiers.",
        "alert.noServerMsg": "Sélectionnez un serveur enregistré ou créez une nouvelle connexion.",
        "alert.bookmarkNotFoundMsg": "Le marque-page nommé %@ est introuvable.",
        "startup.failedTitle": "Impossible de charger Driftline",
        "startup.failedDescription": "Une erreur s\'est produite lors du chargement de l\'application.",
        "startup.retry": "Réessayer",

        "app.name": "Driftline",
        "alert.ok": "OK",
        "sidebar.contextConnect": "Connecter",
        "sidebar.contextEdit": "Modifier",
        "browser.upOneFolder": "Dossier parent",
        "browser.refreshPane": "Actualiser %@",
        "browser.emptyRemote": "Aucune liste distante",
        "browser.emptyLocal": "Ce dossier est vide",
        "browser.emptyRemoteMessage": "Créez une connexion, sélectionnez un serveur enregistré, puis appuyez sur Connecter.",
        "browser.emptyLocalMessage": "Créez un dossier ou choisissez un autre chemin local.",
        "browser.goTo": "Aller à %@",
        "browser.macintoshHD": "Macintosh HD",
        "browser.loading": "Chargement...",
        "browser.loadingAccessibility": "Chargement",
        "browser.column.name": "Nom",
        "browser.column.size": "Taille",
        "browser.column.type": "Type",
        "browser.column.modified": "Modifié",
        "browser.fileBrowser": "Navigateur de fichiers %@",
        "browser.copyPath": "Copier le chemin",
        "browser.revealFinder": "Afficher dans le Finder",
        "browser.getInfo": "Informations",
        "browser.rename": "Renommer",
        "browser.delete": "Supprimer",
        "browser.modifiedAccessibility": "Modifié %@",
        "browser.selectedAccessibility": "%@ sélectionné",
        "browser.column.accessibility": "%@ : %@",
        "transfer.column.status": "Statut",
        "transfer.column.progress": "Progression",
        "transfer.column.direction": "Direction",
        "transfer.column.source": "Source",
        "transfer.column.destination": "Destination",
        "transfer.column.server": "Serveur",
        "transfer.column.action": "Action",
        "transfer.cancelTransfer": "Annuler le transfert",
        "transfer.cancelTransferAccessibility": "Annuler le transfert",
        "transfer.completed": "Terminés",
        "transfer.noTransfers": "Aucun transfert pour l’instant",
        "transfer.emptyMessage": "Les téléversements et téléchargements apparaîtront ici.",
        "transfer.transfers": "Transferts",
        "transfer.filter": "Filtre des transferts",
        "transfer.filter.active": "Actifs",
        "transfer.filter.all": "Tous",
        "transfer.filter.completed": "Terminés",
        "transfer.filter.failed": "Échoués",
        "transfer.noFilteredTransfers": "Aucun transfert dans cette vue",
        "transfer.noFilteredTransfersMessage": "Choisissez un autre filtre de transferts.",
        "transfer.cancelActive": "Annuler actifs",
        "transfer.retryFailed": "Réessayer échoués",
        "transfer.clearFailed": "Effacer échoués",
        "transfer.clearCompleted": "Effacer terminés",
        "transfer.cancelActiveHelp": "Annuler actifs",
        "transfer.retryFailedHelp": "Réessayer échoués",
        "transfer.clearFailedHelp": "Effacer échoués",
        "transfer.clearCompletedHelp": "Effacer terminés",
        "transfer.cancelsActiveHint": "Annule les transferts actifs.",
        "transfer.retriesFailedHint": "Réessaie les transferts échoués.",
        "transfer.downloaded": "Téléchargé",
        "transfer.uploaded": "Téléversé",
        "conflict.title": "Conflit de transfert",
        "conflict.existsAt": "Un élément existe déjà à :",
        "conflict.existingDestination": "Destination existante",
        "conflict.renameDestination": "Renommer la destination",
        "conflict.renameHint": "Saisissez un nouveau nom de fichier de destination pour ce transfert uniquement.",
        "conflict.applySingle": "Appliquer Ignorer ou Écraser à %d conflit restant",
        "conflict.applyPlural": "Appliquer Ignorer ou Écraser à %d conflits restants",
        "conflict.applyHint": "Renommer s\'applique toujours uniquement au conflit actuel.",
        "conflict.skip": "Ignorer",
        "conflict.overwrite": "Écraser",
        "conflict.transferRenamed": "Transférer avec renommage",
        "conflict.skipHelpSingle": "Ignorer ce transfert.",
        "conflict.skipHelpMulti": "Ignorer ce transfert et tous les conflits restants.",
        "conflict.skipHint": "Laisse l\'élément existant inchangé.",
        "conflict.overwriteHelpSingle": "Écraser cette destination.",
        "conflict.overwriteHelpMulti": "Écraser cette destination et tous les conflits restants.",
        "conflict.overwriteHint": "Démarre le transfert et remplace l\'élément de destination existant.",
        "conflict.renameHelp": "Transférer cet élément en utilisant le champ de renommage.",
        "sync.done": "Terminé",
        "sync.closeHint": "Ferme la comparaison de dossiers.",
        "sync.matching": "Identiques",
        "sync.localOnly": "Local seulement",
        "sync.remoteOnly": "Distant seulement",
        "sync.changed": "Modifiés",
        "sync.changedConflicts": "Conflits modifiés",
        "sync.conflictHint": "Contrôle comment les fichiers modifiés sont gérés lorsque les deux côtés ont déjà un élément.",
        "sync.planned": "%d prévus",
        "sync.runPlan": "Exécuter le plan",
        "sync.runPlanHint": "Démarre les téléversements et téléchargements sélectionnés.",
        "sync.onlyLocal": "Local seulement",
        "sync.onlyRemote": "Distant seulement",
        "sync.nothingToUpload": "Rien à téléverser.",
        "sync.nothingToDownload": "Rien à télécharger.",
        "sync.none": "Aucun",
        "sync.all": "Tout",
        "sync.toggleAllHint": "Bascule tous les éléments de cette section.",
        "sync.setAll": "Définir tout",
        "sync.skip": "Ignorer",
        "sync.uploadLocalVersions": "Téléverser versions locales",
        "sync.downloadRemoteVersions": "Télécharger versions distantes",
        "sync.setAllHint": "Choisissez si les versions locales ou distantes doivent gagner.",
        "sync.noDifferences": "Aucune différence de taille ou de type.",
        "sync.action": "Action",
        "sync.ask": "Demander",
        "sync.replace": "Remplacer",
        "sync.skipChanged": "Ignorer modifiés",
        "trust.title": "Faire confiance à l\'hôte ?",
        "trust.algorithm": "Algorithme",
        "trust.fingerprint": "Empreinte",
        "trust.warning": "Ne faites confiance à cet hôte que si l\'empreinte correspond à une valeur que vous avez vérifiée hors bande.",
        "trust.trustAndConnect": "Faire confiance et connecter",
        "trust.hint": "Enregistre cette empreinte dans les hôtes connus de Driftline et reconnecte.",
        "fileOperation.name": "Nom",
        "fileOperation.save": "Enregistrer",
        "fileOperation.cancel": "Annuler",
        "profile.section.server": "Serveur",
        "profile.section.authentication": "Authentification",
        "profile.section.paths": "Chemins",
        "profile.section.metadata": "Métadonnées",
        "profile.displayName": "Nom d\'affichage",
        "profile.host": "Hôte",
        "profile.protocol": "Protocole",
        "profile.port": "Port",
        "profile.group": "Groupe",
        "profile.favorite": "Favori",
        "profile.username": "Nom d\'utilisateur",
        "profile.method": "Méthode",
        "profile.auth.agent": "Agent SSH",
        "profile.auth.none": "Aucune",
        "profile.auth.password": "Mot de passe",
        "profile.auth.privateKey": "Clé privée",
        "profile.password": "Mot de passe",
        "profile.privateKey": "Clé privée",
        "profile.privateKeyPath": "Chemin de la clé privée",
        "profile.choose": "Choisir...",
        "profile.storePassphrase": "Enregistrer la phrase secrète dans le Trousseau",
        "profile.privateKeyPassphrase": "Phrase secrète de la clé privée",
        "profile.noAuth": "Aucune",
        "profile.passwordNote": "Le mot de passe est stocké dans le Trousseau. Driftline utilise automatiquement le backend SSH natif Swift pour les connexions par mot de passe.",
        "profile.remotePath": "Chemin distant par défaut",
        "profile.localPath": "Chemin local par défaut",
        "profile.tags": "Étiquettes",
        "profile.notes": "Notes",
        "profile.tagsPrompt": "production, site-web",
        "profile.saveConnect": "Enregistrer et connecter",
        "profile.save": "Enregistrer",
        "profile.newServer": "Nouveau serveur",
        "viewOptions.browser": "Navigateur",
        "viewOptions.panels": "Panneaux",
        "inspector.selection": "Sélection",
        "inspector.actions": "Actions",
        "inspector.activity": "Activité",
        "inspector.chooseServer": "Choisissez un serveur dans la barre latérale pour afficher ses informations.",
        "inspector.connection": "Connexion",
        "inspector.copyRemotePath": "Copier le chemin distant",
        "inspector.lastActivity": "Dernière activité",
        "inspector.name": "Nom",
        "inspector.noItemSelected": "Aucun élément sélectionné",
        "inspector.noServerSelected": "Aucun serveur sélectionné",
        "inspector.path": "Chemin",
        "inspector.permissions": "Permissions",
        "inspector.quickLook": "Coup d'œil",
        "inspector.server": "Serveur",
        "inspector.type": "Type",
        "inspector.size": "Taille",
        "inspector.source": "Source",
        "inspector.selectItem": "Sélectionnez un élément local ou distant pour afficher les détails et les actions.",
        "inspector.state": "État",
        "inspector.protocol": "Protocole",
        "inspector.localPath": "Chemin local",
        "inspector.remotePath": "Chemin distant",
        "stats.uploads": "Téléversements",
        "stats.downloads": "Téléchargements",
        "stats.uploaded": "Téléversé",
        "stats.downloaded": "Téléchargé",
        "stats.active": "Actifs",
        "stats.failed": "Échoués",
        "stats.lastConnection": "Dernière connexion",
        "stats.lastConnectionFormat": "Dernière connexion : %@",
        "stats.up": "Montés",
        "stats.down": "Descendus",
        "about.tagline": "Transfert de fichiers natif, sereinement sécurisé.",
        "about.freeMessage": "Driftline est entièrement gratuit. Si cela vous aide, n\'hésitez pas à faire un don.",
        "about.donate": "Faire un don sur Ko-fi",
        "about.checking": "Vérification...",
        "about.checkForUpdates": "Vérifier les mises à jour",
        "about.diagnostics": "Diagnostics",
        "about.version": "Version %@ (%@)",
    ],
    .german: [
        "appearance.dark": "Dunkel",
        "appearance.light": "Hell",
        "appearance.system": "System",
        "backend.nativeSwiftSSH": "Natives Swift SSH",
        "backend.systemSSH": "System-SSH",
        "common.no": "Nein",
        "common.none": "Keine",
        "common.server": "Server",
        "common.yes": "Ja",
        "settings.general": "Allgemein",
        "settings.about": "Info",
        "settings.language": "Sprache",
        "settings.appearance": "Erscheinungsbild",
        "settings.behavior": "Verhalten",
        "settings.transfers": "Übertragungen",
        "settings.notifications": "Benachrichtigungen",
        "settings.showHiddenFiles": "Versteckte Dateien anzeigen",
        "settings.confirmBeforeDelete": "Vor Löschen bestätigen",
        "settings.confirmBeforeOverwrite": "Vor Überschreiben bestätigen",
        "settings.checkUpdatesOnStartup": "Beim Start nach Updates suchen",
        "settings.backgroundNotifications": "Hintergrundbenachrichtigungen",
        "settings.transferConcurrency": "Gleichzeitige Übertragungen",
        "settings.remoteBackend": "Remote-Backend",
        "settings.appIcon": "App-Symbol",
        "settings.theme": "Design",
        "settings.defaultSort": "Standardsortierung",
        "settings.languagePicker": "App-Sprache",
        "settings.showInspector": "Inspektor anzeigen",
        "settings.showTransferQueue": "Übertragungswarteschlange",
        "settings.showSidebar": "Seitenleiste anzeigen",
        "settings.showFileExtensions": "Dateiendungen anzeigen",
        "settings.foldersFirst": "Ordner zuerst",
        "settings.sortBy": "Sortieren nach",
        "settings.ascending": "Aufsteigend",
        "settings.browser": "Browser",
        "settings.panels": "Panels",
        "settings.backend.native": "Experimentell: natives SFTP unterstützt Passwort- und Private-Key-Workflows; System-SSH für SSH-Agent-Auth verwenden.",
        "settings.backend.system": "Empfohlen: verwendet macOS SSH-Shell-Tools mit strenger Host-Prüfung, SSH-Agent-Unterstützung und rsync-Übertragungen.",
        "browser.local": "Lokal",
        "browser.remote": "Remote",
        "browser.refresh": "Aktualisieren",
        "browser.refreshRemote": "Remote aktualisieren",
        "browser.upload": "Hochladen",
        "browser.download": "Herunterladen",
        "browser.compare": "Vergleichen",
        "browser.newFolder": "Neuer Ordner",
        "browser.viewOptions": "Ansichtsoptionen",
        "browser.inspector": "Inspektor",
        "browser.refreshHint": "Aktualisiert die lokale Dateiliste.",
        "browser.refreshRemoteHint": "Aktualisiert die Remote-Dateiliste.",
        "browser.uploadHint": "Lädt das ausgewählte lokale Element in den Remote-Ordner hoch.",
        "browser.downloadHint": "Lädt das ausgewählte Remote-Element in den lokalen Ordner herunter.",
        "browser.compareHint": "Vergleicht die aktuellen lokalen und Remote-Ordner.",
        "browser.connectToServer": "Mit Server verbinden",
        "browser.filterFiles": "Dateien filtern...",
        "browser.itemCount": "%d Elemente",
        "browser.noFilterResults": "Keine passenden Dateien",
        "browser.noFilterResultsMessage": "Passen Sie den Filter an, um Dateien in diesem Bereich anzuzeigen.",
        "browser.noRemoteConnection": "Keine Remote-Verbindung",
        "browser.noRemoteConnectionMessage": "Wählen Sie einen gespeicherten Server oder erstellen Sie eine neue SFTP-Verbindung.",
        "connection.connect": "Verbinden",
        "connection.connecting": "Verbinden...",
        "connection.disconnect": "Trennen",
        "connection.new": "Neu",
        "connection.more": "Mehr",
        "connection.edit": "Bearbeiten",
        "connection.favorite": "Favorit",
        "connection.bookmark": "Lesezeichen",
        "connection.terminal": "Terminal",
        "connection.noServer": "Kein Server ausgewählt",
        "connection.connected": "Verbunden",
        "connection.disconnected": "Getrennt",
        "connection.failed": "Fehlgeschlagen",
        "connection.cancelling": "Abbrechen",
        "connection.reconnecting": "Neu verbinden",
        "connection.connectHint": "Verbindet zum ausgewählten gespeicherten Server.",
        "connection.newHint": "Öffnet ein neues Verbindungsformular.",
        "connection.editHint": "Ausgewählten Server bearbeiten.",
        "connection.addFavHint": "Ausgewählten Server zu Favoriten hinzufügen.",
        "connection.removeFavHint": "Ausgewählten Server aus Favoriten entfernen.",
        "connection.bookmarkHint": "Aktuelle lokale und Remote-Pfade als Lesezeichen speichern.",
        "connection.terminalHint": "Öffnet eine SSH-Sitzung im Terminal.",
        "connection.disconnectHint": "Vom aktuellen Server trennen.",
        "connection.connectionStatus": "Verbindungsstatus: %@",
        "sidebar.driftline": "Driftline",
        "sidebar.newConnection": "Neue Verbindung",
        "sidebar.saveServer": "Server speichern",
        "sidebar.savedServers": "Gespeicherte Server",
        "sidebar.favorites": "Favoriten",
        "sidebar.bookmarks": "Lesezeichen",
        "sidebar.recent": "Kürzlich",
        "sidebar.noSavedServers": "Keine gespeicherten Server",
        "sidebar.markFavorites": "Server als Favoriten markieren",
        "sidebar.noBookmarks": "Keine Lesezeichen gespeichert",
        "sidebar.noBookmarksDetail": "Fügen Sie Ordner hinzu, um schnell darauf zuzugreifen.",
        "sidebar.noRecent": "Keine kürzlichen Verbindungen",
        "sidebar.quickConnect": "Schnellverbindung",
        "sidebar.recentServers": "Kürzliche Server",
        "transfer.queued": "Wartend",
        "transfer.done": "Fertig",
        "transfer.failed": "Fehlgeschlagen",
        "transfer.cancelled": "Abgebrochen",
        "tab.newConnection": "Neue Verbindung",
        "tab.closeTab": "Tab schließen?",
        "tab.close": "Schließen",
        "tab.cancel": "Abbrechen",
        "tab.closeConfirm.connected": "Die Verbindung zu %@ ist noch aktiv. Das Schließen dieses Tabs trennt die Verbindung.",
        "tab.closeConfirm.connecting": "Die Verbindung zu %@ wird aufgebaut. Das Schließen dieses Tabs trennt die Verbindung.",
        "tab.closeConfirm.reconnecting": "Die Verbindung zu %@ wird wiederhergestellt. Das Schließen dieses Tabs trennt die Verbindung.",
        "tab.closeConfirm.default": "Die Verbindung zu %@ ist aktiv. Das Schließen dieses Tabs trennt die Verbindung.",
        "tab.closeAction": "Tab schließen",
        "update.available": "Update verfügbar",
        "update.later": "Später",
        "update.download": "Update herunterladen",
        "update.message": "Driftline %@ ist verfügbar. Sie verwenden %@.",
        "update.notificationBody": "Version %@ ist zum Herunterladen bereit.",
        "update.notificationTitle": "Driftline-Update verfügbar",
        "update.upToDate": "Driftline ist aktuell.",
        "update.checkFailed": "Update-Prüfung fehlgeschlagen:",
        "delete.title": "Löschen?",
        "delete.message": "Dieses Element wird gelöscht.",
        "delete.delete": "Löschen",
        "delete.cancel": "Abbrechen",
        "file.newFolder": "Neuer Ordner",
        "file.renameItem": "Umbenennen",
        "file.newLocalFolder": "Neuer lokaler Ordner",
        "file.newRemoteFolder": "Neuer Remote-Ordner",
        "file.newSourceFolder": "Neuer %@-Ordner",
        "fileKind.file": "Datei",
        "fileKind.folder": "Ordner",
        "fileKind.symbolicLink": "Symbolischer Link",
        "fileKind.unknown": "Unbekannt",
        "menu.file": "Ablage",
        "menu.newConnection": "Neue Verbindung",
        "menu.newTab": "Neuer Tab",
        "menu.closeTab": "Tab schließen",
        "menu.connection": "Verbindung",
        "menu.quickConnect": "Schnellverbindung",
        "menu.connectSelected": "Ausgewählten Server verbinden",
        "menu.openSSH": "SSH im Terminal öffnen",
        "menu.reconnectLast": "Letzten neu verbinden",
        "menu.saveConnection": "Aktuelle Verbindung speichern",
        "menu.transfer": "Transfer",
        "menu.upload": "Hochladen",
        "menu.download": "Herunterladen",
        "menu.compareFolders": "Ordner vergleichen",
        "menu.showInspector": "Inspektor anzeigen",
        "menu.viewOptions": "Ansichtsoptionen",
        "menu.help": "Hilfe",
        "menu.checkUpdates": "Nach Updates suchen",
        "menu.revealDiagnostics": "Diagnoseprotokoll anzeigen",
        "menu.copy": "Kopieren",
        "menu.paste": "Einsetzen",
        "menu.aboutDriftline": "Über Driftline",
        "menu.edit": "Bearbeiten",
        "menu.duplicate": "Duplizieren",
        "menu.delete": "Löschen",

        "toast.upToDate": "Driftline ist aktuell.",
        "toast.copiedSingle": "%@ kopiert.",
        "toast.copiedMulti": "%d Elemente kopiert.",
        "toast.syncStartedSingle": "1 Synchronisierungsübertragung gestartet.",
        "toast.syncStartedMulti": "%d Synchronisierungsübertragungen gestartet.",
        "toast.favoriteAdded": "Zu Favoriten hinzugefügt.",
        "toast.favoriteRemoved": "Aus Favoriten entfernt.",
        "toast.bookmarkSaved": "Lesezeichen gespeichert.",
        "toast.nativeSSHSwitch": "Auf natives Swift SSH für Passwort-Authentifizierung umgeschaltet.",
        "notification.serverDisconnectedBody": "%@ ist nicht mehr erreichbar.",
        "notification.serverDisconnectedTitle": "Server getrennt",
        "notification.transferCompletedBody": "%@ auf %@ abgeschlossen.",
        "notification.transferCompletedTitle": "%@ %@",
        "notification.transferFailedBody": "%@ auf %@ fehlgeschlagen.",
        "notification.transferFailedTitle": "%@ fehlgeschlagen",
        "alert.checkUpdatesTitle": "Update-Prüfung nicht möglich",
        "alert.unsupportedTitle": "Nicht unterstützte Aktion",
        "alert.notConnectedTitle": "Nicht verbunden",
        "alert.noServerTitle": "Kein Server ausgewählt",
        "alert.bookmarkNotFoundTitle": "Lesezeichen nicht gefunden",
        "alert.favoriteFailedTitle": "Favorit konnte nicht aktualisiert werden",
        "alert.bookmarkSaveFailedTitle": "Lesezeichen konnte nicht gespeichert werden",
        "alert.copyFailedTitle": "Kopieren nicht möglich",
        "alert.unsupportedMsg": "Kopieren von Remote zu Remote wird noch nicht unterstützt.",
        "alert.notConnectedMsg": "Verbinden Sie sich mit einem Server, bevor Sie Ordner vergleichen.",
        "alert.noServerMsg": "Wählen Sie einen gespeicherten Server oder erstellen Sie eine neue Verbindung.",
        "alert.bookmarkNotFoundMsg": "Lesezeichen mit Namen %@ wurde nicht gefunden.",
        "startup.failedTitle": "Driftline konnte nicht geladen werden",
        "startup.failedDescription": "Beim Laden der Anwendung ist ein Fehler aufgetreten.",
        "startup.retry": "Erneut versuchen",

        "app.name": "Driftline",
        "alert.ok": "OK",
        "sidebar.contextConnect": "Verbinden",
        "sidebar.contextEdit": "Bearbeiten",
        "browser.upOneFolder": "Übergeordneter Ordner",
        "browser.refreshPane": "%@ aktualisieren",
        "browser.emptyRemote": "Keine Remote-Liste",
        "browser.emptyLocal": "Dieser Ordner ist leer",
        "browser.emptyRemoteMessage": "Erstellen Sie eine Verbindung, wählen Sie einen gespeicherten Server und klicken Sie auf Verbinden.",
        "browser.emptyLocalMessage": "Erstellen Sie einen Ordner oder wählen Sie einen anderen lokalen Pfad.",
        "browser.goTo": "Gehe zu %@",
        "browser.macintoshHD": "Macintosh HD",
        "browser.loading": "Laden...",
        "browser.loadingAccessibility": "Laden",
        "browser.column.name": "Name",
        "browser.column.size": "Größe",
        "browser.column.type": "Typ",
        "browser.column.modified": "Geändert",
        "browser.fileBrowser": "%@ Dateibrowser",
        "browser.copyPath": "Pfad kopieren",
        "browser.revealFinder": "Im Finder anzeigen",
        "browser.getInfo": "Informationen",
        "browser.rename": "Umbenennen",
        "browser.delete": "Löschen",
        "browser.modifiedAccessibility": "Geändert %@",
        "browser.selectedAccessibility": "%@ ausgewählt",
        "browser.column.accessibility": "%@: %@",
        "transfer.column.status": "Status",
        "transfer.column.progress": "Fortschritt",
        "transfer.column.direction": "Richtung",
        "transfer.column.source": "Quelle",
        "transfer.column.destination": "Ziel",
        "transfer.column.server": "Server",
        "transfer.column.action": "Aktion",
        "transfer.cancelTransfer": "Übertragung abbrechen",
        "transfer.cancelTransferAccessibility": "Übertragung abbrechen",
        "transfer.completed": "Abgeschlossen",
        "transfer.noTransfers": "Noch keine Übertragungen",
        "transfer.emptyMessage": "Uploads und Downloads erscheinen hier.",
        "transfer.transfers": "Übertragungen",
        "transfer.filter": "Übertragungsfilter",
        "transfer.filter.active": "Aktiv",
        "transfer.filter.all": "Alle",
        "transfer.filter.completed": "Abgeschlossen",
        "transfer.filter.failed": "Fehlgeschlagen",
        "transfer.noFilteredTransfers": "Keine Übertragungen in dieser Ansicht",
        "transfer.noFilteredTransfersMessage": "Wählen Sie einen anderen Übertragungsfilter.",
        "transfer.cancelActive": "Aktive abbrechen",
        "transfer.retryFailed": "Fehlgeschlagene wiederholen",
        "transfer.clearFailed": "Fehlgeschlagene löschen",
        "transfer.clearCompleted": "Abgeschlossene löschen",
        "transfer.cancelActiveHelp": "Aktive abbrechen",
        "transfer.retryFailedHelp": "Fehlgeschlagene wiederholen",
        "transfer.clearFailedHelp": "Fehlgeschlagene löschen",
        "transfer.clearCompletedHelp": "Abgeschlossene löschen",
        "transfer.cancelsActiveHint": "Bricht aktive Übertragungen ab.",
        "transfer.retriesFailedHint": "Wiederholt fehlgeschlagene Übertragungen.",
        "transfer.downloaded": "Heruntergeladen",
        "transfer.uploaded": "Hochgeladen",
        "conflict.title": "Übertragungskonflikt",
        "conflict.existsAt": "Ein Element existiert bereits unter:",
        "conflict.existingDestination": "Vorhandenes Ziel",
        "conflict.renameDestination": "Ziel umbenennen",
        "conflict.renameHint": "Geben Sie einen neuen Zieldateinamen nur für diese Übertragung ein.",
        "conflict.applySingle": "Überspringen oder Überschreiben auf %d verbleibenden Konflikt anwenden",
        "conflict.applyPlural": "Überspringen oder Überschreiben auf %d verbleibende Konflikte anwenden",
        "conflict.applyHint": "Umbenennen gilt immer nur für den aktuellen Konflikt.",
        "conflict.skip": "Überspringen",
        "conflict.overwrite": "Überschreiben",
        "conflict.transferRenamed": "Umbenannt übertragen",
        "conflict.skipHelpSingle": "Diese Übertragung überspringen.",
        "conflict.skipHelpMulti": "Diese und alle verbleibenden Konflikte überspringen.",
        "conflict.skipHint": "Lässt das vorhandene Element unverändert.",
        "conflict.overwriteHelpSingle": "Dieses Ziel überschreiben.",
        "conflict.overwriteHelpMulti": "Dieses und alle verbleibenden Ziele überschreiben.",
        "conflict.overwriteHint": "Startet die Übertragung und ersetzt das vorhandene Zielelement.",
        "conflict.renameHelp": "Dieses Element mit dem Umbenennungsfeld übertragen.",
        "sync.done": "Fertig",
        "sync.closeHint": "Schließt den Ordnervergleich.",
        "sync.matching": "Übereinstimmend",
        "sync.localOnly": "Nur lokal",
        "sync.remoteOnly": "Nur remote",
        "sync.changed": "Geändert",
        "sync.changedConflicts": "Geänderte Konflikte",
        "sync.conflictHint": "Legt fest, wie geänderte Dateien behandelt werden, wenn beide Seiten bereits ein Element haben.",
        "sync.planned": "%d geplant",
        "sync.runPlan": "Plan ausführen",
        "sync.runPlanHint": "Startet ausgewählte Uploads und Downloads.",
        "sync.onlyLocal": "Nur lokal",
        "sync.onlyRemote": "Nur remote",
        "sync.nothingToUpload": "Nichts hochzuladen.",
        "sync.nothingToDownload": "Nichts herunterzuladen.",
        "sync.none": "Keine",
        "sync.all": "Alle",
        "sync.toggleAllHint": "Schaltet alle Elemente in diesem Abschnitt um.",
        "sync.setAll": "Alle setzen",
        "sync.skip": "Überspringen",
        "sync.uploadLocalVersions": "Lokale Versionen hochladen",
        "sync.downloadRemoteVersions": "Remote-Versionen herunterladen",
        "sync.setAllHint": "Wählen Sie, ob lokale oder Remote-Versionen gewinnen sollen.",
        "sync.noDifferences": "Keine Größen- oder Typunterschiede.",
        "sync.action": "Aktion",
        "sync.ask": "Fragen",
        "sync.replace": "Ersetzen",
        "sync.skipChanged": "Geänderte überspringen",
        "trust.title": "Host vertrauen?",
        "trust.algorithm": "Algorithmus",
        "trust.fingerprint": "Fingerabdruck",
        "trust.warning": "Vertrauen Sie diesem Host nur, wenn der Fingerabdruck mit einem von Ihnen außerhalb des Programms überprüften Wert übereinstimmt.",
        "trust.trustAndConnect": "Vertrauen und verbinden",
        "trust.hint": "Speichert diesen Fingerabdruck in den bekannten Hosts von Driftline und verbindet erneut.",
        "fileOperation.name": "Name",
        "fileOperation.save": "Speichern",
        "fileOperation.cancel": "Abbrechen",
        "profile.section.server": "Server",
        "profile.section.authentication": "Authentifizierung",
        "profile.section.paths": "Pfade",
        "profile.section.metadata": "Metadaten",
        "profile.displayName": "Anzeigename",
        "profile.host": "Host",
        "profile.protocol": "Protokoll",
        "profile.port": "Port",
        "profile.group": "Gruppe",
        "profile.favorite": "Favorit",
        "profile.username": "Benutzername",
        "profile.method": "Methode",
        "profile.auth.agent": "SSH-Agent",
        "profile.auth.none": "Keine",
        "profile.auth.password": "Passwort",
        "profile.auth.privateKey": "Privater Schlüssel",
        "profile.password": "Passwort",
        "profile.privateKey": "Privater Schlüssel",
        "profile.privateKeyPath": "Pfad zum privaten Schlüssel",
        "profile.choose": "Auswählen...",
        "profile.storePassphrase": "Passphrase in Schlüsselbund speichern",
        "profile.privateKeyPassphrase": "Private-Key-Passphrase",
        "profile.noAuth": "Keine",
        "profile.passwordNote": "Das Passwort wird im Schlüsselbund gespeichert. Driftline verwendet automatisch das native Swift-SSH-Backend für passwortbasierte Verbindungen.",
        "profile.remotePath": "Remote-Standardpfad",
        "profile.localPath": "Lokaler Standardpfad",
        "profile.tags": "Tags",
        "profile.notes": "Notizen",
        "profile.tagsPrompt": "produktion, website",
        "profile.saveConnect": "Speichern & verbinden",
        "profile.save": "Speichern",
        "profile.newServer": "Neuer Server",
        "viewOptions.browser": "Browser",
        "viewOptions.panels": "Panels",
        "inspector.selection": "Auswahl",
        "inspector.actions": "Aktionen",
        "inspector.activity": "Aktivität",
        "inspector.chooseServer": "Wählen Sie einen Server aus der Seitenleiste, um Informationen anzuzeigen.",
        "inspector.connection": "Verbindung",
        "inspector.copyRemotePath": "Remote-Pfad kopieren",
        "inspector.lastActivity": "Letzte Aktivität",
        "inspector.name": "Name",
        "inspector.noItemSelected": "Kein Element ausgewählt",
        "inspector.noServerSelected": "Kein Server ausgewählt",
        "inspector.path": "Pfad",
        "inspector.permissions": "Berechtigungen",
        "inspector.quickLook": "Übersicht",
        "inspector.server": "Server",
        "inspector.type": "Typ",
        "inspector.size": "Größe",
        "inspector.source": "Quelle",
        "inspector.selectItem": "Wählen Sie ein lokales oder Remote-Element aus, um Details und Aktionen anzuzeigen.",
        "inspector.state": "Status",
        "inspector.protocol": "Protokoll",
        "inspector.localPath": "Lokaler Pfad",
        "inspector.remotePath": "Remote-Pfad",
        "stats.uploads": "Uploads",
        "stats.downloads": "Downloads",
        "stats.uploaded": "Hochgeladen",
        "stats.downloaded": "Heruntergeladen",
        "stats.active": "Aktiv",
        "stats.failed": "Fehlgeschlagen",
        "stats.lastConnection": "Letzte Verbindung",
        "stats.lastConnectionFormat": "Letzte Verbindung: %@",
        "stats.up": "Hoch",
        "stats.down": "Runter",
        "about.tagline": "Nativer Dateitransfer, gelassen sicher.",
        "about.freeMessage": "Driftline ist völlig kostenlos. Wenn es Ihnen hilft, können Sie gerne spenden.",
        "about.donate": "Auf Ko-fi spenden",
        "about.checking": "Prüfen...",
        "about.checkForUpdates": "Nach Updates suchen",
        "about.diagnostics": "Diagnose",
        "about.version": "Version %@ (%@)",
    ],
    .spanish: [
        "appearance.dark": "Oscuro",
        "appearance.light": "Claro",
        "appearance.system": "Sistema",
        "backend.nativeSwiftSSH": "SSH nativo de Swift",
        "backend.systemSSH": "SSH del sistema",
        "common.no": "No",
        "common.none": "Ninguna",
        "common.server": "servidor",
        "common.yes": "Sí",
        "settings.general": "General",
        "settings.about": "Acerca de",
        "settings.language": "Idioma",
        "settings.appearance": "Apariencia",
        "settings.behavior": "Comportamiento",
        "settings.transfers": "Transferencias",
        "settings.notifications": "Notificaciones",
        "settings.showHiddenFiles": "Mostrar archivos ocultos",
        "settings.confirmBeforeDelete": "Confirmar antes de eliminar",
        "settings.confirmBeforeOverwrite": "Confirmar antes de sobrescribir",
        "settings.checkUpdatesOnStartup": "Buscar actualizaciones al iniciar",
        "settings.backgroundNotifications": "Notificaciones en segundo plano",
        "settings.transferConcurrency": "Transferencias simultáneas",
        "settings.remoteBackend": "Backend remoto",
        "settings.appIcon": "Icono de la app",
        "settings.theme": "Tema",
        "settings.defaultSort": "Orden predeterminado",
        "settings.languagePicker": "Idioma de la app",
        "settings.showInspector": "Mostrar inspector",
        "settings.showTransferQueue": "Mostrar cola de transferencia",
        "settings.showSidebar": "Mostrar barra lateral",
        "settings.showFileExtensions": "Mostrar extensiones",
        "settings.foldersFirst": "Carpetas primero",
        "settings.sortBy": "Ordenar por",
        "settings.ascending": "Ascendente",
        "settings.browser": "Navegador",
        "settings.panels": "Paneles",
        "settings.backend.native": "Experimental: SFTP nativo admite flujos con contraseña y clave privada; use SSH del sistema para autenticación con agente SSH.",
        "settings.backend.system": "Recomendado: usa las herramientas SSH del sistema macOS con verificación estricta de host, soporte de agente SSH y transferencias rsync.",
        "browser.local": "Local",
        "browser.remote": "Remoto",
        "browser.refresh": "Actualizar",
        "browser.refreshRemote": "Actualizar remoto",
        "browser.upload": "Subir",
        "browser.download": "Descargar",
        "browser.compare": "Comparar",
        "browser.newFolder": "Nueva carpeta",
        "browser.viewOptions": "Opciones de vista",
        "browser.inspector": "Inspector",
        "browser.refreshHint": "Actualiza la lista de archivos locales.",
        "browser.refreshRemoteHint": "Actualiza la lista de archivos remotos.",
        "browser.uploadHint": "Sube el elemento local seleccionado a la carpeta remota.",
        "browser.downloadHint": "Descarga el elemento remoto seleccionado a la carpeta local.",
        "browser.compareHint": "Compara las carpetas local y remota actuales.",
        "browser.connectToServer": "Conectar a un servidor",
        "browser.filterFiles": "Filtrar archivos…",
        "browser.itemCount": "%d elementos",
        "browser.noFilterResults": "No hay archivos coincidentes",
        "browser.noFilterResultsMessage": "Ajuste el filtro para mostrar archivos en este panel.",
        "browser.noRemoteConnection": "Sin conexión remota",
        "browser.noRemoteConnectionMessage": "Seleccione un servidor guardado o cree una nueva conexión SFTP.",
        "connection.connect": "Conectar",
        "connection.connecting": "Conectando...",
        "connection.disconnect": "Desconectar",
        "connection.new": "Nuevo",
        "connection.more": "Más",
        "connection.edit": "Editar",
        "connection.favorite": "Favorito",
        "connection.bookmark": "Marcador",
        "connection.terminal": "Terminal",
        "connection.noServer": "Sin servidor seleccionado",
        "connection.connected": "Conectado",
        "connection.disconnected": "Desconectado",
        "connection.failed": "Fallido",
        "connection.cancelling": "Cancelando",
        "connection.reconnecting": "Reconectando",
        "connection.connectHint": "Conecta al servidor guardado seleccionado.",
        "connection.newHint": "Abre un formulario de nueva conexión.",
        "connection.editHint": "Editar el servidor seleccionado.",
        "connection.addFavHint": "Añadir el servidor seleccionado a favoritos.",
        "connection.removeFavHint": "Quitar el servidor seleccionado de favoritos.",
        "connection.bookmarkHint": "Guardar las rutas local y remota actuales como marcador.",
        "connection.terminalHint": "Abre una sesión SSH en Terminal.",
        "connection.disconnectHint": "Desconectar del servidor actual.",
        "connection.connectionStatus": "Estado de la conexión: %@",
        "sidebar.driftline": "Driftline",
        "sidebar.newConnection": "Nueva conexión",
        "sidebar.saveServer": "Guardar servidor",
        "sidebar.savedServers": "Servidores guardados",
        "sidebar.favorites": "Favoritos",
        "sidebar.bookmarks": "Marcadores",
        "sidebar.recent": "Recientes",
        "sidebar.noSavedServers": "Sin servidores guardados",
        "sidebar.markFavorites": "Marcar servidores como favoritos",
        "sidebar.noBookmarks": "Sin marcadores guardados",
        "sidebar.noBookmarksDetail": "Agregue carpetas para acceder a ellas rápidamente.",
        "sidebar.noRecent": "Sin conexiones recientes",
        "sidebar.quickConnect": "Conexión rápida",
        "sidebar.recentServers": "Servidores recientes",
        "transfer.queued": "En cola",
        "transfer.done": "Completado",
        "transfer.failed": "Fallido",
        "transfer.cancelled": "Cancelado",
        "tab.newConnection": "Nueva conexión",
        "tab.closeTab": "¿Cerrar pestaña?",
        "tab.close": "Cerrar",
        "tab.cancel": "Cancelar",
        "tab.closeConfirm.connected": "La conexión a %@ sigue activa. Cerrar esta pestaña desconectará.",
        "tab.closeConfirm.connecting": "La conexión a %@ se está estableciendo. Cerrar esta pestaña desconectará.",
        "tab.closeConfirm.reconnecting": "La reconexión a %@ está en curso. Cerrar esta pestaña desconectará.",
        "tab.closeConfirm.default": "La conexión a %@ está activa. Cerrar esta pestaña desconectará.",
        "tab.closeAction": "Cerrar pestaña",
        "update.available": "Actualización disponible",
        "update.later": "Más tarde",
        "update.download": "Descargar actualización",
        "update.message": "Driftline %@ está disponible. Está usando la versión %@.",
        "update.notificationBody": "La versión %@ está lista para descargar.",
        "update.notificationTitle": "Actualización de Driftline disponible",
        "update.upToDate": "Driftline está actualizado.",
        "update.checkFailed": "No se pudo verificar actualizaciones:",
        "delete.title": "¿Eliminar?",
        "delete.message": "Este elemento será eliminado.",
        "delete.delete": "Eliminar",
        "delete.cancel": "Cancelar",
        "file.newFolder": "Nueva carpeta",
        "file.renameItem": "Renombrar",
        "file.newLocalFolder": "Nueva carpeta local",
        "file.newRemoteFolder": "Nueva carpeta remota",
        "file.newSourceFolder": "Nueva carpeta %@",
        "fileKind.file": "Archivo",
        "fileKind.folder": "Carpeta",
        "fileKind.symbolicLink": "Enlace simbólico",
        "fileKind.unknown": "Desconocido",
        "menu.file": "Archivo",
        "menu.newConnection": "Nueva conexión",
        "menu.newTab": "Nueva pestaña",
        "menu.closeTab": "Cerrar pestaña",
        "menu.connection": "Conexión",
        "menu.quickConnect": "Conexión rápida",
        "menu.connectSelected": "Conectar servidor seleccionado",
        "menu.openSSH": "Abrir SSH en Terminal",
        "menu.reconnectLast": "Reconectar último",
        "menu.saveConnection": "Guardar conexión actual",
        "menu.transfer": "Transferencia",
        "menu.upload": "Subir",
        "menu.download": "Descargar",
        "menu.compareFolders": "Comparar carpetas",
        "menu.showInspector": "Mostrar inspector",
        "menu.viewOptions": "Opciones de vista",
        "menu.help": "Ayuda",
        "menu.checkUpdates": "Buscar actualizaciones",
        "menu.revealDiagnostics": "Mostrar registro de diagnóstico",
        "menu.copy": "Copiar",
        "menu.paste": "Pegar",
        "menu.aboutDriftline": "Acerca de Driftline",
        "menu.edit": "Editar",
        "menu.duplicate": "Duplicar",
        "menu.delete": "Eliminar",

        "toast.upToDate": "Driftline está actualizado.",
        "toast.copiedSingle": "%@ copiado.",
        "toast.copiedMulti": "%d elementos copiados.",
        "toast.syncStartedSingle": "1 transferencia de sincronización iniciada.",
        "toast.syncStartedMulti": "%d transferencias de sincronización iniciadas.",
        "toast.favoriteAdded": "Añadido a favoritos.",
        "toast.favoriteRemoved": "Eliminado de favoritos.",
        "toast.bookmarkSaved": "Marcador guardado.",
        "toast.nativeSSHSwitch": "Cambiado a SSH nativo de Swift para autenticación por contraseña.",
        "notification.serverDisconnectedBody": "%@ ya no está disponible.",
        "notification.serverDisconnectedTitle": "Servidor desconectado",
        "notification.transferCompletedBody": "%@ terminó en %@.",
        "notification.transferCompletedTitle": "%@ %@",
        "notification.transferFailedBody": "%@ falló en %@.",
        "notification.transferFailedTitle": "%@ fallida",
        "alert.checkUpdatesTitle": "No se pudieron buscar actualizaciones",
        "alert.unsupportedTitle": "Acción no compatible",
        "alert.notConnectedTitle": "No conectado",
        "alert.noServerTitle": "Sin servidor seleccionado",
        "alert.bookmarkNotFoundTitle": "Marcador no encontrado",
        "alert.favoriteFailedTitle": "No se pudo actualizar el favorito",
        "alert.bookmarkSaveFailedTitle": "No se pudo guardar el marcador",
        "alert.copyFailedTitle": "No se pudo copiar",
        "alert.unsupportedMsg": "La copia de remoto a remoto aún no es compatible.",
        "alert.notConnectedMsg": "Conéctese a un servidor antes de comparar carpetas.",
        "alert.noServerMsg": "Seleccione un servidor guardado o cree una nueva conexión.",
        "alert.bookmarkNotFoundMsg": "El marcador llamado %@ no fue encontrado.",
        "startup.failedTitle": "No se pudo cargar Driftline",
        "startup.failedDescription": "Ocurrió un error al cargar la aplicación.",
        "startup.retry": "Reintentar",

        "app.name": "Driftline",
        "alert.ok": "OK",
        "sidebar.contextConnect": "Conectar",
        "sidebar.contextEdit": "Editar",
        "browser.upOneFolder": "Carpeta superior",
        "browser.refreshPane": "Actualizar %@",
        "browser.emptyRemote": "Sin listado remoto",
        "browser.emptyLocal": "Esta carpeta está vacía",
        "browser.emptyRemoteMessage": "Cree una conexión, seleccione un servidor guardado y presione Conectar.",
        "browser.emptyLocalMessage": "Cree una carpeta o elija otra ruta local.",
        "browser.goTo": "Ir a %@",
        "browser.macintoshHD": "Macintosh HD",
        "browser.loading": "Cargando...",
        "browser.loadingAccessibility": "Cargando",
        "browser.column.name": "Nombre",
        "browser.column.size": "Tamaño",
        "browser.column.type": "Tipo",
        "browser.column.modified": "Modificado",
        "browser.fileBrowser": "Explorador de archivos %@",
        "browser.copyPath": "Copiar ruta",
        "browser.revealFinder": "Mostrar en Finder",
        "browser.getInfo": "Información",
        "browser.rename": "Renombrar",
        "browser.delete": "Eliminar",
        "browser.modifiedAccessibility": "Modificado %@",
        "browser.selectedAccessibility": "%@ seleccionado",
        "browser.column.accessibility": "%@: %@",
        "transfer.column.status": "Estado",
        "transfer.column.progress": "Progreso",
        "transfer.column.direction": "Dirección",
        "transfer.column.source": "Origen",
        "transfer.column.destination": "Destino",
        "transfer.column.server": "Servidor",
        "transfer.column.action": "Acción",
        "transfer.cancelTransfer": "Cancelar transferencia",
        "transfer.cancelTransferAccessibility": "Cancelar transferencia",
        "transfer.completed": "Completadas",
        "transfer.noTransfers": "Aún no hay transferencias",
        "transfer.emptyMessage": "Las subidas y descargas aparecerán aquí.",
        "transfer.transfers": "Transferencias",
        "transfer.filter": "Filtro de transferencias",
        "transfer.filter.active": "Activas",
        "transfer.filter.all": "Todas",
        "transfer.filter.completed": "Completadas",
        "transfer.filter.failed": "Fallidas",
        "transfer.noFilteredTransfers": "No hay transferencias en esta vista",
        "transfer.noFilteredTransfersMessage": "Elija otro filtro de transferencias.",
        "transfer.cancelActive": "Cancelar activas",
        "transfer.retryFailed": "Reintentar fallidas",
        "transfer.clearFailed": "Limpiar fallidas",
        "transfer.clearCompleted": "Limpiar completadas",
        "transfer.cancelActiveHelp": "Cancelar activas",
        "transfer.retryFailedHelp": "Reintentar fallidas",
        "transfer.clearFailedHelp": "Limpiar fallidas",
        "transfer.clearCompletedHelp": "Limpiar completadas",
        "transfer.cancelsActiveHint": "Cancela las transferencias activas.",
        "transfer.retriesFailedHint": "Reintenta las transferencias fallidas.",
        "transfer.downloaded": "Descargado",
        "transfer.uploaded": "Subido",
        "conflict.title": "Conflicto de transferencia",
        "conflict.existsAt": "Ya existe un elemento en:",
        "conflict.existingDestination": "Destino existente",
        "conflict.renameDestination": "Renombrar destino",
        "conflict.renameHint": "Ingrese un nuevo nombre de archivo de destino solo para esta transferencia.",
        "conflict.applySingle": "Aplicar Omitir o Sobrescribir a %d conflicto restante",
        "conflict.applyPlural": "Aplicar Omitir o Sobrescribir a %d conflictos restantes",
        "conflict.applyHint": "Renombrar siempre se aplica solo al conflicto actual.",
        "conflict.skip": "Omitir",
        "conflict.overwrite": "Sobrescribir",
        "conflict.transferRenamed": "Transferir renombrado",
        "conflict.skipHelpSingle": "Omitir esta transferencia.",
        "conflict.skipHelpMulti": "Omitir esta y todos los conflictos restantes.",
        "conflict.skipHint": "Deja el elemento existente sin cambios.",
        "conflict.overwriteHelpSingle": "Sobrescribir este destino.",
        "conflict.overwriteHelpMulti": "Sobrescribir este y todos los destinos restantes.",
        "conflict.overwriteHint": "Inicia la transferencia y reemplaza el elemento de destino existente.",
        "conflict.renameHelp": "Transferir este elemento usando el campo de renombrar.",
        "sync.done": "Hecho",
        "sync.closeHint": "Cierra la comparación de carpetas.",
        "sync.matching": "Coincidentes",
        "sync.localOnly": "Solo local",
        "sync.remoteOnly": "Solo remoto",
        "sync.changed": "Modificados",
        "sync.changedConflicts": "Conflictos modificados",
        "sync.conflictHint": "Controla cómo se manejan los archivos modificados cuando ambos lados ya tienen un elemento.",
        "sync.planned": "%d planificadas",
        "sync.runPlan": "Ejecutar plan",
        "sync.runPlanHint": "Inicia las subidas y descargas seleccionadas.",
        "sync.onlyLocal": "Solo local",
        "sync.onlyRemote": "Solo remoto",
        "sync.nothingToUpload": "Nada para subir.",
        "sync.nothingToDownload": "Nada para descargar.",
        "sync.none": "Ninguno",
        "sync.all": "Todo",
        "sync.toggleAllHint": "Alterna todos los elementos de esta sección.",
        "sync.setAll": "Establecer todo",
        "sync.skip": "Omitir",
        "sync.uploadLocalVersions": "Subir versiones locales",
        "sync.downloadRemoteVersions": "Descargar versiones remotas",
        "sync.setAllHint": "Elija si las versiones locales o remotas deben ganar.",
        "sync.noDifferences": "Sin diferencias de tamaño o tipo.",
        "sync.action": "Acción",
        "sync.ask": "Preguntar",
        "sync.replace": "Reemplazar",
        "sync.skipChanged": "Omitir modificados",
        "trust.title": "¿Confiar en el host?",
        "trust.algorithm": "Algoritmo",
        "trust.fingerprint": "Huella digital",
        "trust.warning": "Solo confíe en este host si la huella coincide con un valor que verificó fuera de banda.",
        "trust.trustAndConnect": "Confiar y conectar",
        "trust.hint": "Almacena esta huella en los hosts conocidos de Driftline y reconecta.",
        "fileOperation.name": "Nombre",
        "fileOperation.save": "Guardar",
        "fileOperation.cancel": "Cancelar",
        "profile.section.server": "Servidor",
        "profile.section.authentication": "Autenticación",
        "profile.section.paths": "Rutas",
        "profile.section.metadata": "Metadatos",
        "profile.displayName": "Nombre visible",
        "profile.host": "Host",
        "profile.protocol": "Protocolo",
        "profile.port": "Puerto",
        "profile.group": "Grupo",
        "profile.favorite": "Favorito",
        "profile.username": "Usuario",
        "profile.method": "Método",
        "profile.auth.agent": "Agente SSH",
        "profile.auth.none": "Ninguna",
        "profile.auth.password": "Contraseña",
        "profile.auth.privateKey": "Clave privada",
        "profile.password": "Contraseña",
        "profile.privateKey": "Clave privada",
        "profile.privateKeyPath": "Ruta de clave privada",
        "profile.choose": "Elegir...",
        "profile.storePassphrase": "Guardar frase de contraseña en Keychain",
        "profile.privateKeyPassphrase": "Frase de clave privada",
        "profile.noAuth": "Ninguna",
        "profile.passwordNote": "La contraseña se almacena en Keychain. Driftline usa automáticamente el backend SSH nativo de Swift para conexiones por contraseña.",
        "profile.remotePath": "Ruta remota predeterminada",
        "profile.localPath": "Ruta local predeterminada",
        "profile.tags": "Etiquetas",
        "profile.notes": "Notas",
        "profile.tagsPrompt": "producción, sitio-web",
        "profile.saveConnect": "Guardar y conectar",
        "profile.save": "Guardar",
        "profile.newServer": "Nuevo servidor",
        "viewOptions.browser": "Navegador",
        "viewOptions.panels": "Paneles",
        "inspector.selection": "Selección",
        "inspector.actions": "Acciones",
        "inspector.activity": "Actividad",
        "inspector.chooseServer": "Elija un servidor en la barra lateral para ver información.",
        "inspector.connection": "Conexión",
        "inspector.copyRemotePath": "Copiar ruta remota",
        "inspector.lastActivity": "Última actividad",
        "inspector.name": "Nombre",
        "inspector.noItemSelected": "Ningún elemento seleccionado",
        "inspector.noServerSelected": "Ningún servidor seleccionado",
        "inspector.path": "Ruta",
        "inspector.permissions": "Permisos",
        "inspector.quickLook": "Vista rápida",
        "inspector.server": "Servidor",
        "inspector.type": "Tipo",
        "inspector.size": "Tamaño",
        "inspector.source": "Origen",
        "inspector.selectItem": "Seleccione un elemento local o remoto para ver detalles y acciones.",
        "inspector.state": "Estado",
        "inspector.protocol": "Protocolo",
        "inspector.localPath": "Ruta local",
        "inspector.remotePath": "Ruta remota",
        "stats.uploads": "Subidas",
        "stats.downloads": "Descargas",
        "stats.uploaded": "Subido",
        "stats.downloaded": "Descargado",
        "stats.active": "Activas",
        "stats.failed": "Fallidas",
        "stats.lastConnection": "Última conexión",
        "stats.lastConnectionFormat": "Última conexión: %@",
        "stats.up": "Sub",
        "stats.down": "Baj",
        "about.tagline": "Transferencia de archivos nativa, serenamente segura.",
        "about.freeMessage": "Driftline es completamente gratuito. Si le ayuda, siéntase libre de donar.",
        "about.donate": "Donar en Ko-fi",
        "about.checking": "Verificando...",
        "about.checkForUpdates": "Buscar actualizaciones",
        "about.diagnostics": "Diagnóstico",
        "about.version": "Versión %@ (%@)",
    ],
]
